name: Deploy Django to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v3

      - name: 2. Create ZIP file for deployment
        # Comprime el código de la aplicación, excluyendo archivos innecesarios.
        # El archivo .ebextensions es crucial, así que se incluye.
        run: zip -r deploy.zip . -x ".git/*" "venv/*" "__pycache__/*" "*.env" "docs/*" "README.md" "core (2).zip" "core.zip" "env/*"

      - name: 3. Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "pharmacontrol"
          environment_name: "Pharmacontrol-env"
          region: "us-east-2"
          
          # Etiqueta de versión siempre única usando SHA y timestamp
          version_label: "deploy-${{ github.sha }}-${{ github.run_id }}"
          
          deployment_package: deploy.zip
          wait_for_deployment: true
          use_existing_version_if_available: true
          
          # Bucket S3 explícito
          bucket_name: "elasticbeanstalk-us-east-2-467433242511"
